### ISSUE TITLE
tpmstream-web no longer works

### ISSUE THREAD

**Issue by sun2sirius** [joholl/tpmstream#28]
The https://joholl.github.io/tpmstream-web/ page used to work like in Oct 2024, but now it displays packages = ["tpmstream"] Detect... and nothing happens - it looks broken.

Then I installed the tpmstream python package with "pip install tpmstream" - TPM commands are interpreted correctly, but when I send a TPM response it throws an exception:
```
  File "C:\Python3\Lib\site-packages\tpmstream\io\binary\marshal.py", line 498, in process_command                                                              
    raise ValueConstraintViolatedError(                                         
tpmstream.common.error.ValueConstraintViolatedError: Parsed bad value for TPM_CC .commandCode = 0x0 = 0 not in ValidValues(TPM_CC)                              
```
I am pretty sure when web interface worked, I was able to decode commands and responses. It looks like the response is treated as command or something. Maybe I am not doing it correctly - for both command and response streams I do the same:
```
tpmstream convert mybytes.txt
```

**Comment by rcolombanWis** [comment]
The web page still does not work

By default the data must have a command and response. If it's only a response you have to add more options, for example:
`tpmstream --type Response --command StartAuthSession --in hex convert mybytes.txt`

**Comment by sun2sirius** [comment]
Thank you so much @rcolombanWis ! I was able to make it work by concatenating command and response into one stream - I certainly missed this. Then I was also able to decode the response only, but had to place the arguments in different order, it did not work exactly as suggested (I run on Windows). The command lines that worked for me were as below:
```
tpmstream convert --type Response --command CreatePrimary --in binary mybytes.bin
tpmstream convert --type Response --command CreatePrimary --in hex mybytes.txt
```
Apparently, "convert" needs to go first. Also, --in binary/hex is necessary for Response, while for Command only and Command+Response I can simply do:
```
tpmstream convert mybytes.bin
tpmstream convert mybytes.txt
```
